return {
   "echasnovski/mini.surround",
   event = "VeryLazy",
   opts = {
      modes = { insert = true, command = true, terminal = false },
      skip_ts = { "string" },
      skip_unbalanced = true,
      markdown = true,
      mappings = {
         add = "gsa",
         delete = "gsd",
         find = "gsf",
         find_left = "gsF",
         highlight = "gsh",
         replace = "gsr",
         update_n_lines = "gsn",
      },
   },
   keys = {
      mode = { "n", "v" },
      { "gs", group = "Surrounding" },
      { "gsa", desc = "Add Surrounding" },
      { "gsd", desc = "Delete Surrounding" },
      { "gsf", desc = "Find Right Surrounding" },
      { "gsF", desc = "Find Left Surrounding" },
      { "gsh", desc = "Highlight Surrounding" },
      { "gsr", desc = "Replace Surrounding" },
      { "gsn", desc = "Update n lines" },
   },
}
